import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={cn("flex min-h-[100dvh]", poppins.className)}>
        <Toaster
          richColors
          theme="dark"
          position="bottom-center"
          duration={2500}
        />
        <SessionProvider session={session}>
          <div className="flex-1">{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
